import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";

const c = { bold: "\x1b[1m", green: "\x1b[32m", cyan: "\x1b[36m", dim: "\x1b[2m", yellow: "\x1b[33m", reset: "\x1b[0m" };

function randomHex(bytes: number): string {
  return Array.from(crypto.getRandomValues(new Uint8Array(bytes)))
    .map(b => b.toString(16).padStart(2, "0")).join("");
}

export async function init() {
  console.log(`\n${c.cyan}${c.bold}⬡ Sovereignly Init${c.reset}\n`);

  // Create data directory
  await mkdir("data/platform", { recursive: true });
  console.log(`${c.green}✓${c.reset} Created data/platform/`);

  // Generate .env if not exists
  if (existsSync(".env")) {
    console.log(`${c.yellow}!${c.reset} .env already exists — skipping`);
  } else {
    const serverKey = randomHex(32);
    const jwtSecret = randomHex(32);
    const adminToken = randomHex(16);

    const env = `# Sovereignly v4.0.0 — Generated by 'sovereignly init'
SOVEREIGN_SERVER_KEY=${serverKey}
JWT_SECRET=${jwtSecret}
ADMIN_TOKEN=${adminToken}
PORT=8787
DATA_DIR=./data
ANCHOR_TIER=free
`;
    await Bun.write(".env", env);
    console.log(`${c.green}✓${c.reset} Generated .env with secure random secrets`);
    console.log(`${c.dim}  SOVEREIGN_SERVER_KEY=${serverKey.slice(0, 8)}...${c.reset}`);
    console.log(`${c.dim}  ADMIN_TOKEN=${adminToken.slice(0, 8)}...${c.reset}`);
  }

  console.log(`\n${c.bold}Next steps:${c.reset}`);
  console.log(`  ${c.cyan}sovereignly dev${c.reset}       Start the server`);
  console.log(`  ${c.cyan}sovereignly status${c.reset}    Check health`);
  console.log(`  ${c.cyan}sovereignly emit${c.reset}      Send a test event`);
  console.log();
}
